'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SAT
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://cancelacfd.sat.gob.mx", ConfigurationName:="SAT.ICancelaCFDBinding")>  _
    Public Interface ICancelaCFDBinding
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://cancelacfd.sat.gob.mx/ICancelaCFDBinding/CancelaCFD", ReplyAction:="http://cancelacfd.sat.gob.mx/ICancelaCFDBinding/CancelaCFDResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CancelaCFD(ByVal Cancelacion As SAT.Cancelacion) As SAT.Acuse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cancelacfd.sat.gob.mx")>  _
    Partial Public Class Cancelacion
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private foliosField() As CancelacionFolios
        
        Private signatureField As SignatureType
        
        Private rfcEmisorField As String
        
        Private fechaField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Folios", Order:=0)>  _
        Public Property Folios() As CancelacionFolios()
            Get
                Return Me.foliosField
            End Get
            Set
                Me.foliosField = value
                Me.RaisePropertyChanged("Folios")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", Order:=1)>  _
        Public Property Signature() As SignatureType
            Get
                Return Me.signatureField
            End Get
            Set
                Me.signatureField = value
                Me.RaisePropertyChanged("Signature")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property RfcEmisor() As String
            Get
                Return Me.rfcEmisorField
            End Get
            Set
                Me.rfcEmisorField = value
                Me.RaisePropertyChanged("RfcEmisor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
                Me.RaisePropertyChanged("Fecha")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://cancelacfd.sat.gob.mx")>  _
    Partial Public Class CancelacionFolios
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private uUIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
                Me.RaisePropertyChanged("UUID")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cancelacfd.sat.gob.mx")>  _
    Partial Public Class Acuse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private foliosField() As AcuseFolios
        
        Private signatureField As SignatureType
        
        Private codEstatusField As String
        
        Private fechaField As Date
        
        Private rfcEmisorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Folios", Order:=0)>  _
        Public Property Folios() As AcuseFolios()
            Get
                Return Me.foliosField
            End Get
            Set
                Me.foliosField = value
                Me.RaisePropertyChanged("Folios")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", Order:=1)>  _
        Public Property Signature() As SignatureType
            Get
                Return Me.signatureField
            End Get
            Set
                Me.signatureField = value
                Me.RaisePropertyChanged("Signature")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property CodEstatus() As String
            Get
                Return Me.codEstatusField
            End Get
            Set
                Me.codEstatusField = value
                Me.RaisePropertyChanged("CodEstatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
                Me.RaisePropertyChanged("Fecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property RfcEmisor() As String
            Get
                Return Me.rfcEmisorField
            End Get
            Set
                Me.rfcEmisorField = value
                Me.RaisePropertyChanged("RfcEmisor")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://cancelacfd.sat.gob.mx")>  _
    Partial Public Class AcuseFolios
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private uUIDField As String
        
        Private estatusUUIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
                Me.RaisePropertyChanged("UUID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property EstatusUUID() As String
            Get
                Return Me.estatusUUIDField
            End Get
            Set
                Me.estatusUUIDField = value
                Me.RaisePropertyChanged("EstatusUUID")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignatureType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private signedInfoField As SignedInfoType
        
        Private signatureValueField() As Byte
        
        Private keyInfoField As KeyInfoType
        
        Private objectField() As ObjectType
        
        Private idField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property SignedInfo() As SignedInfoType
            Get
                Return Me.signedInfoField
            End Get
            Set
                Me.signedInfoField = value
                Me.RaisePropertyChanged("SignedInfo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=1)>  _
        Public Property SignatureValue() As Byte()
            Get
                Return Me.signatureValueField
            End Get
            Set
                Me.signatureValueField = value
                Me.RaisePropertyChanged("SignatureValue")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property KeyInfo() As KeyInfoType
            Get
                Return Me.keyInfoField
            End Get
            Set
                Me.keyInfoField = value
                Me.RaisePropertyChanged("KeyInfo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Object", Order:=3)>  _
        Public Property [Object]() As ObjectType()
            Get
                Return Me.objectField
            End Get
            Set
                Me.objectField = value
                Me.RaisePropertyChanged("Object")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignedInfoType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private canonicalizationMethodField As CanonicalizationMethodType
        
        Private signatureMethodField As SignatureMethodType
        
        Private referenceField As ReferenceType
        
        Private idField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property CanonicalizationMethod() As CanonicalizationMethodType
            Get
                Return Me.canonicalizationMethodField
            End Get
            Set
                Me.canonicalizationMethodField = value
                Me.RaisePropertyChanged("CanonicalizationMethod")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property SignatureMethod() As SignatureMethodType
            Get
                Return Me.signatureMethodField
            End Get
            Set
                Me.signatureMethodField = value
                Me.RaisePropertyChanged("SignatureMethod")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Reference() As ReferenceType
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
                Me.RaisePropertyChanged("Reference")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class CanonicalizationMethodType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute(Order:=0)>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
                Me.RaisePropertyChanged("Any")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
                Me.RaisePropertyChanged("Algorithm")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignatureMethodType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private hMACOutputLengthField As String
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", Order:=0)>  _
        Public Property HMACOutputLength() As String
            Get
                Return Me.hMACOutputLengthField
            End Get
            Set
                Me.hMACOutputLengthField = value
                Me.RaisePropertyChanged("HMACOutputLength")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute(Order:=1)>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
                Me.RaisePropertyChanged("Any")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
                Me.RaisePropertyChanged("Algorithm")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class ReferenceType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private transformsField() As TransformType
        
        Private digestMethodField As DigestMethodType
        
        Private digestValueField() As Byte
        
        Private idField As String
        
        Private uRIField As String
        
        Private typeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=false)>  _
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set
                Me.transformsField = value
                Me.RaisePropertyChanged("Transforms")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property DigestMethod() As DigestMethodType
            Get
                Return Me.digestMethodField
            End Get
            Set
                Me.digestMethodField = value
                Me.RaisePropertyChanged("DigestMethod")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=2)>  _
        Public Property DigestValue() As Byte()
            Get
                Return Me.digestValueField
            End Get
            Set
                Me.digestValueField = value
                Me.RaisePropertyChanged("DigestValue")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set
                Me.uRIField = value
                Me.RaisePropertyChanged("URI")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
                Me.RaisePropertyChanged("Type")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class TransformType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private xPathField As String
        
        Private textField() As String
        
        Private algorithmField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property XPath() As String
            Get
                Return Me.xPathField
            End Get
            Set
                Me.xPathField = value
                Me.RaisePropertyChanged("XPath")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
                Me.RaisePropertyChanged("Algorithm")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class DigestMethodType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute(Order:=0)>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
                Me.RaisePropertyChanged("Any")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
                Me.RaisePropertyChanged("Algorithm")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class KeyInfoType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private x509DataField As X509DataType
        
        Private keyNameField As String
        
        Private keyValueField As KeyValueType
        
        Private textField() As String
        
        Private idField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property X509Data() As X509DataType
            Get
                Return Me.x509DataField
            End Get
            Set
                Me.x509DataField = value
                Me.RaisePropertyChanged("X509Data")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property KeyName() As String
            Get
                Return Me.keyNameField
            End Get
            Set
                Me.keyNameField = value
                Me.RaisePropertyChanged("KeyName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property KeyValue() As KeyValueType
            Get
                Return Me.keyValueField
            End Get
            Set
                Me.keyValueField = value
                Me.RaisePropertyChanged("KeyValue")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class X509DataType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private x509IssuerSerialField As X509IssuerSerialType
        
        Private x509CertificateField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property X509IssuerSerial() As X509IssuerSerialType
            Get
                Return Me.x509IssuerSerialField
            End Get
            Set
                Me.x509IssuerSerialField = value
                Me.RaisePropertyChanged("X509IssuerSerial")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=1)>  _
        Public Property X509Certificate() As Byte()
            Get
                Return Me.x509CertificateField
            End Get
            Set
                Me.x509CertificateField = value
                Me.RaisePropertyChanged("X509Certificate")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class X509IssuerSerialType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private x509IssuerNameField As String
        
        Private x509SerialNumberField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property X509IssuerName() As String
            Get
                Return Me.x509IssuerNameField
            End Get
            Set
                Me.x509IssuerNameField = value
                Me.RaisePropertyChanged("X509IssuerName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer", Order:=1)>  _
        Public Property X509SerialNumber() As String
            Get
                Return Me.x509SerialNumberField
            End Get
            Set
                Me.x509SerialNumberField = value
                Me.RaisePropertyChanged("X509SerialNumber")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class KeyValueType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private rSAKeyValueField As RSAKeyValueType
        
        Private textField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property RSAKeyValue() As RSAKeyValueType
            Get
                Return Me.rSAKeyValueField
            End Get
            Set
                Me.rSAKeyValueField = value
                Me.RaisePropertyChanged("RSAKeyValue")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class RSAKeyValueType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private modulusField() As Byte
        
        Private exponentField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=0)>  _
        Public Property Modulus() As Byte()
            Get
                Return Me.modulusField
            End Get
            Set
                Me.modulusField = value
                Me.RaisePropertyChanged("Modulus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=1)>  _
        Public Property Exponent() As Byte()
            Get
                Return Me.exponentField
            End Get
            Set
                Me.exponentField = value
                Me.RaisePropertyChanged("Exponent")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class ObjectType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private anyField() As System.Xml.XmlNode
        
        Private idField As String
        
        Private mimeTypeField As String
        
        Private encodingField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute(Order:=0)>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
                Me.RaisePropertyChanged("Any")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MimeType() As String
            Get
                Return Me.mimeTypeField
            End Get
            Set
                Me.mimeTypeField = value
                Me.RaisePropertyChanged("MimeType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Encoding() As String
            Get
                Return Me.encodingField
            End Get
            Set
                Me.encodingField = value
                Me.RaisePropertyChanged("Encoding")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICancelaCFDBindingChannel
        Inherits SAT.ICancelaCFDBinding, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CancelaCFDBindingClient
        Inherits System.ServiceModel.ClientBase(Of SAT.ICancelaCFDBinding)
        Implements SAT.ICancelaCFDBinding
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CancelaCFD(ByVal Cancelacion As SAT.Cancelacion) As SAT.Acuse Implements SAT.ICancelaCFDBinding.CancelaCFD
            Return MyBase.Channel.CancelaCFD(Cancelacion)
        End Function
    End Class
End Namespace
