'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace AztecaSoftwareCFDI
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="http://www.aztecasoftware.mx/", ItemName:="string"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.aztecasoftware.mx/", ConfigurationName:="AztecaSoftwareCFDI.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        'CODEGEN: Generating message contract since element name usuario from namespace http://www.aztecasoftware.mx/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.aztecasoftware.mx/IniciarSesion", ReplyAction:="*")>  _
        Function IniciarSesion(ByVal request As AztecaSoftwareCFDI.IniciarSesionRequest) As AztecaSoftwareCFDI.IniciarSesionResponse
        
        'CODEGEN: Generating message contract since element name sessionID from namespace http://www.aztecasoftware.mx/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.aztecasoftware.mx/Timbrar", ReplyAction:="*")>  _
        Function Timbrar(ByVal request As AztecaSoftwareCFDI.TimbrarRequest) As AztecaSoftwareCFDI.TimbrarResponse
        
        'CODEGEN: Generating message contract since element name sessionID from namespace http://www.aztecasoftware.mx/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.aztecasoftware.mx/Cancelar", ReplyAction:="*")>  _
        Function Cancelar(ByVal request As AztecaSoftwareCFDI.CancelarRequest) As AztecaSoftwareCFDI.CancelarResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class IniciarSesionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="IniciarSesion", [Namespace]:="http://www.aztecasoftware.mx/", Order:=0)>  _
        Public Body As AztecaSoftwareCFDI.IniciarSesionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AztecaSoftwareCFDI.IniciarSesionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.aztecasoftware.mx/")>  _
    Partial Public Class IniciarSesionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal password As String)
            MyBase.New
            Me.usuario = usuario
            Me.password = password
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class IniciarSesionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="IniciarSesionResponse", [Namespace]:="http://www.aztecasoftware.mx/", Order:=0)>  _
        Public Body As AztecaSoftwareCFDI.IniciarSesionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AztecaSoftwareCFDI.IniciarSesionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.aztecasoftware.mx/")>  _
    Partial Public Class IniciarSesionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public IniciarSesionResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal IniciarSesionResult As String)
            MyBase.New
            Me.IniciarSesionResult = IniciarSesionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TimbrarRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Timbrar", [Namespace]:="http://www.aztecasoftware.mx/", Order:=0)>  _
        Public Body As AztecaSoftwareCFDI.TimbrarRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AztecaSoftwareCFDI.TimbrarRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.aztecasoftware.mx/")>  _
    Partial Public Class TimbrarRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public sessionID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public cfdi As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sessionID As String, ByVal cfdi As String)
            MyBase.New
            Me.sessionID = sessionID
            Me.cfdi = cfdi
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TimbrarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TimbrarResponse", [Namespace]:="http://www.aztecasoftware.mx/", Order:=0)>  _
        Public Body As AztecaSoftwareCFDI.TimbrarResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AztecaSoftwareCFDI.TimbrarResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.aztecasoftware.mx/")>  _
    Partial Public Class TimbrarResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public TimbrarResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TimbrarResult As String)
            MyBase.New
            Me.TimbrarResult = TimbrarResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CancelarRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Cancelar", [Namespace]:="http://www.aztecasoftware.mx/", Order:=0)>  _
        Public Body As AztecaSoftwareCFDI.CancelarRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AztecaSoftwareCFDI.CancelarRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.aztecasoftware.mx/")>  _
    Partial Public Class CancelarRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public sessionID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public folios As AztecaSoftwareCFDI.ArrayOfString
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public rfcEmisor As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public certificado As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public llavePrivada As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public passwordPK As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sessionID As String, ByVal folios As AztecaSoftwareCFDI.ArrayOfString, ByVal rfcEmisor As String, ByVal certificado As String, ByVal llavePrivada As String, ByVal passwordPK As String)
            MyBase.New
            Me.sessionID = sessionID
            Me.folios = folios
            Me.rfcEmisor = rfcEmisor
            Me.certificado = certificado
            Me.llavePrivada = llavePrivada
            Me.passwordPK = passwordPK
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CancelarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CancelarResponse", [Namespace]:="http://www.aztecasoftware.mx/", Order:=0)>  _
        Public Body As AztecaSoftwareCFDI.CancelarResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As AztecaSoftwareCFDI.CancelarResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.aztecasoftware.mx/")>  _
    Partial Public Class CancelarResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CancelarResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CancelarResult As String)
            MyBase.New
            Me.CancelarResult = CancelarResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits AztecaSoftwareCFDI.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of AztecaSoftwareCFDI.ServiceSoap)
        Implements AztecaSoftwareCFDI.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AztecaSoftwareCFDI_ServiceSoap_IniciarSesion(ByVal request As AztecaSoftwareCFDI.IniciarSesionRequest) As AztecaSoftwareCFDI.IniciarSesionResponse Implements AztecaSoftwareCFDI.ServiceSoap.IniciarSesion
            Return MyBase.Channel.IniciarSesion(request)
        End Function
        
        Public Function IniciarSesion(ByVal usuario As String, ByVal password As String) As String
            Dim inValue As AztecaSoftwareCFDI.IniciarSesionRequest = New AztecaSoftwareCFDI.IniciarSesionRequest()
            inValue.Body = New AztecaSoftwareCFDI.IniciarSesionRequestBody()
            inValue.Body.usuario = usuario
            inValue.Body.password = password
            Dim retVal As AztecaSoftwareCFDI.IniciarSesionResponse = CType(Me,AztecaSoftwareCFDI.ServiceSoap).IniciarSesion(inValue)
            Return retVal.Body.IniciarSesionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AztecaSoftwareCFDI_ServiceSoap_Timbrar(ByVal request As AztecaSoftwareCFDI.TimbrarRequest) As AztecaSoftwareCFDI.TimbrarResponse Implements AztecaSoftwareCFDI.ServiceSoap.Timbrar
            Return MyBase.Channel.Timbrar(request)
        End Function
        
        Public Function Timbrar(ByVal sessionID As String, ByVal cfdi As String) As String
            Dim inValue As AztecaSoftwareCFDI.TimbrarRequest = New AztecaSoftwareCFDI.TimbrarRequest()
            inValue.Body = New AztecaSoftwareCFDI.TimbrarRequestBody()
            inValue.Body.sessionID = sessionID
            inValue.Body.cfdi = cfdi
            Dim retVal As AztecaSoftwareCFDI.TimbrarResponse = CType(Me,AztecaSoftwareCFDI.ServiceSoap).Timbrar(inValue)
            Return retVal.Body.TimbrarResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AztecaSoftwareCFDI_ServiceSoap_Cancelar(ByVal request As AztecaSoftwareCFDI.CancelarRequest) As AztecaSoftwareCFDI.CancelarResponse Implements AztecaSoftwareCFDI.ServiceSoap.Cancelar
            Return MyBase.Channel.Cancelar(request)
        End Function
        
        Public Function Cancelar(ByVal sessionID As String, ByVal folios As AztecaSoftwareCFDI.ArrayOfString, ByVal rfcEmisor As String, ByVal certificado As String, ByVal llavePrivada As String, ByVal passwordPK As String) As String
            Dim inValue As AztecaSoftwareCFDI.CancelarRequest = New AztecaSoftwareCFDI.CancelarRequest()
            inValue.Body = New AztecaSoftwareCFDI.CancelarRequestBody()
            inValue.Body.sessionID = sessionID
            inValue.Body.folios = folios
            inValue.Body.rfcEmisor = rfcEmisor
            inValue.Body.certificado = certificado
            inValue.Body.llavePrivada = llavePrivada
            inValue.Body.passwordPK = passwordPK
            Dim retVal As AztecaSoftwareCFDI.CancelarResponse = CType(Me,AztecaSoftwareCFDI.ServiceSoap).Cancelar(inValue)
            Return retVal.Body.CancelarResult
        End Function
    End Class
End Namespace
