'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Certus.Servicios
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", ConfigurationName:="Certus.Servicios.WsServicios")>  _
    Public Interface WsServicios
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://cfdi.ws2.facturehoy.certus.com/WsServicios/obtenerServiciosRequest", ReplyAction:="http://cfdi.ws2.facturehoy.certus.com/WsServicios/obtenerServiciosResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function obtenerServicios(ByVal request As Certus.Servicios.obtenerServiciosRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Certus.Servicios.obtenerServiciosResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class wsServicioBO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arrayField() As wsServicioBO
        
        Private cantidadCFDIField As Integer
        
        Private folioFinalField As Integer
        
        Private folioInicialField As Integer
        
        Private idProcessField As Integer
        
        Private mensajeField As String
        
        Private nombreServicioField As String
        
        Private serieField As String
        
        Private ultimoFolioUsadoField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("array", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true, Order:=0)>  _
        Public Property array() As wsServicioBO()
            Get
                Return Me.arrayField
            End Get
            Set
                Me.arrayField = value
                Me.RaisePropertyChanged("array")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property cantidadCFDI() As Integer
            Get
                Return Me.cantidadCFDIField
            End Get
            Set
                Me.cantidadCFDIField = value
                Me.RaisePropertyChanged("cantidadCFDI")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property folioFinal() As Integer
            Get
                Return Me.folioFinalField
            End Get
            Set
                Me.folioFinalField = value
                Me.RaisePropertyChanged("folioFinal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property folioInicial() As Integer
            Get
                Return Me.folioInicialField
            End Get
            Set
                Me.folioInicialField = value
                Me.RaisePropertyChanged("folioInicial")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property idProcess() As Integer
            Get
                Return Me.idProcessField
            End Get
            Set
                Me.idProcessField = value
                Me.RaisePropertyChanged("idProcess")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
                Me.RaisePropertyChanged("mensaje")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property nombreServicio() As String
            Get
                Return Me.nombreServicioField
            End Get
            Set
                Me.nombreServicioField = value
                Me.RaisePropertyChanged("nombreServicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
                Me.RaisePropertyChanged("serie")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property ultimoFolioUsado() As Integer
            Get
                Return Me.ultimoFolioUsadoField
            End Get
            Set
                Me.ultimoFolioUsadoField = value
                Me.RaisePropertyChanged("ultimoFolioUsado")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="obtenerServicios", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class obtenerServiciosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public contrasenia As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal contrasenia As String)
            MyBase.New
            Me.usuario = usuario
            Me.contrasenia = contrasenia
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="obtenerServiciosResponse", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class obtenerServiciosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Certus.Servicios.wsServicioBO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Certus.Servicios.wsServicioBO)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WsServiciosChannel
        Inherits Certus.Servicios.WsServicios, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WsServiciosClient
        Inherits System.ServiceModel.ClientBase(Of Certus.Servicios.WsServicios)
        Implements Certus.Servicios.WsServicios
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Certus_Servicios_WsServicios_obtenerServicios(ByVal request As Certus.Servicios.obtenerServiciosRequest) As Certus.Servicios.obtenerServiciosResponse Implements Certus.Servicios.WsServicios.obtenerServicios
            Return MyBase.Channel.obtenerServicios(request)
        End Function
        
        Public Function obtenerServicios(ByVal usuario As String, ByVal contrasenia As String) As Certus.Servicios.wsServicioBO
            Dim inValue As Certus.Servicios.obtenerServiciosRequest = New Certus.Servicios.obtenerServiciosRequest()
            inValue.usuario = usuario
            inValue.contrasenia = contrasenia
            Dim retVal As Certus.Servicios.obtenerServiciosResponse = CType(Me,Certus.Servicios.WsServicios).obtenerServicios(inValue)
            Return retVal.[return]
        End Function
    End Class
End Namespace
