'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Azteca.Business.Compras.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xsl:stylesheet version=&quot;2.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:fn=&quot;http://www.w3.org/2005/xpath-functions&quot; xmlns:cfd=&quot;http://www.sat.gob.mx/cfd/2&quot; xmlns:ecc=&quot;http://www.sat.gob.mx/ecc&quot; xmlns:psgecfd=&quot;http://www.sat.gob.mx/psgecfd&quot; xmlns:divisas=&quot;http://www.sat.gob.mx/divisas&quot; xmlns:detallista=&quot;http://www.sat.gob.mx/detallista&quot; xmlns:ecb=&quot;http://www.sat.gob.mx/ecb&quot; xmlns:implocal=&quot;http://www.sat.gob.mx/i [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CadenaOriginalXSLT_V2() As String
            Get
                Return ResourceManager.GetString("CadenaOriginalXSLT_V2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xsl:stylesheet version=&quot;2.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:fn=&quot;http://www.w3.org/2005/xpath-functions&quot; xmlns:cfd=&quot;http://www.sat.gob.mx/cfd/2&quot; xmlns:ecc=&quot;http://www.sat.gob.mx/ecc&quot; xmlns:psgecfd=&quot;http://www.sat.gob.mx/psgecfd&quot; xmlns:donat=&quot;http://www.sat.gob.mx/donat&quot; xmlns:divisas=&quot;http://www.sat.gob.mx/divisas&quot; xmlns:detallista=&quot;http://www.sat.gob.mx/detallista&quot; xmlns:ecb=&quot;http://www.sat.gob.mx/ec [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CadenaOriginalXSLT_V2_2() As String
            Get
                Return ResourceManager.GetString("CadenaOriginalXSLT_V2_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xsl:stylesheet version=&quot;2.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:fn=&quot;http://www.w3.org/2005/xpath-functions&quot; xmlns:cfdi=&quot;http://www.sat.gob.mx/cfd/3&quot; xmlns:ecc=&quot;http://www.sat.gob.mx/ecc&quot; xmlns:psgecfd=&quot;http://www.sat.gob.mx/psgecfd&quot; xmlns:divisas=&quot;http://www.sat.gob.mx/divisas&quot; xmlns:detallista=&quot;http://www.sat.gob.mx/detallista&quot; xmlns:ecb=&quot;http://www.sat.gob.mx/ecb&quot; xmlns:implocal=&quot;http://www.sat.gob.mx/ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CadenaOriginalXSLT_V3() As String
            Get
                Return ResourceManager.GetString("CadenaOriginalXSLT_V3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xsl:stylesheet version=&quot;2.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:fn=&quot;http://www.w3.org/2005/xpath-functions&quot; xmlns:cfdi=&quot;http://www.sat.gob.mx/cfd/3&quot; xmlns:ecc=&quot;http://www.sat.gob.mx/ecc&quot; xmlns:psgecfd=&quot;http://www.sat.gob.mx/psgecfd&quot; xmlns:donat=&quot;http://www.sat.gob.mx/donat&quot; xmlns:divisas=&quot;http://www.sat.gob.mx/divisas&quot; xmlns:detallista=&quot;http://www.sat.gob.mx/detallista&quot; xmlns:ecb=&quot;http://www.sat.gob.mx/e [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CadenaOriginalXSLT_V3_2() As String
            Get
                Return ResourceManager.GetString("CadenaOriginalXSLT_V3_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xs:schema xmlns=&quot;http://www.sat.gob.mx/cfd/2&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.sat.gob.mx/cfd/2&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        '''  &lt;xs:element name=&quot;Comprobante&quot;&gt;
        '''    &lt;xs:annotation&gt;
        '''      &lt;xs:documentation&gt;Estándar para la expresión de comprobantes fiscales digitales.&lt;/xs:documentation&gt;
        '''    &lt;/xs:annotation&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:sequence&gt;
        '''        &lt;xs:element name=&quot;Emisor&quot;&gt;
        '''    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FacturaXSD_V2() As String
            Get
                Return ResourceManager.GetString("FacturaXSD_V2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xs:schema xmlns=&quot;http://www.sat.gob.mx/cfd/2&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.sat.gob.mx/cfd/2&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        '''	&lt;xs:element name=&quot;Comprobante&quot;&gt;
        '''		&lt;xs:annotation&gt;
        '''			&lt;xs:documentation&gt;Estándar para la expresión de comprobantes fiscales digitales.&lt;/xs:documentation&gt;
        '''		&lt;/xs:annotation&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:sequence&gt;
        '''				&lt;xs:element name=&quot;Emisor&quot;&gt;
        '''					&lt;xs:annotation&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FacturaXSD_V2_2() As String
            Get
                Return ResourceManager.GetString("FacturaXSD_V2_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xs:schema xmlns:cfdi=&quot;http://www.sat.gob.mx/cfd/3&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.sat.gob.mx/cfd/3&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        '''	&lt;xs:element name=&quot;Comprobante&quot;&gt;
        '''		&lt;xs:annotation&gt;
        '''			&lt;xs:documentation&gt;Estándar para la expresión de comprobantes fiscales digitales por Internet.&lt;/xs:documentation&gt;
        '''		&lt;/xs:annotation&gt;
        '''		&lt;xs:complexType&gt;
        '''			&lt;xs:sequence&gt;
        '''				&lt;xs:element name=&quot;Emisor&quot;&gt;
        '''		 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FacturaXSD_V3() As String
            Get
                Return ResourceManager.GetString("FacturaXSD_V3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;!-- edited with XMLSpy v2010 rel. 3 (http://www.altova.com) by SAT (SAT) --&gt;
        '''&lt;xs:schema xmlns:cfdi=&quot;http://www.sat.gob.mx/cfd/3&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.sat.gob.mx/cfd/3&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        '''	&lt;xs:element name=&quot;Comprobante&quot;&gt;
        '''		&lt;xs:annotation&gt;
        '''			&lt;xs:documentation&gt;Estándar de Comprobante fiscal digital a través de Internet.&lt;/xs:documentation&gt;
        '''		&lt;/xs:annotation&gt;
        '''		&lt;xs:co [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FacturaXSD_V3_2() As String
            Get
                Return ResourceManager.GetString("FacturaXSD_V3_2", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
