'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Certus.Timbrado
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", ConfigurationName:="Certus.Timbrado.WsEmisionTimbrado")>  _
    Public Interface WsEmisionTimbrado
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/EmitirTimbrarRequest", ReplyAction:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/EmitirTimbrarResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EmitirTimbrar(ByVal request As Certus.Timbrado.EmitirTimbrarRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Certus.Timbrado.EmitirTimbrarResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/EmitirTimbrarTestRequest", ReplyAction:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/EmitirTimbrarTestResponse"& _ 
            ""),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EmitirTimbrarTest(ByVal request As Certus.Timbrado.EmitirTimbrarTestRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Certus.Timbrado.EmitirTimbrarTestResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/CancelarRequest", ReplyAction:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/CancelarResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Cancelar(ByVal request As Certus.Timbrado.CancelarRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Certus.Timbrado.CancelarResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/RecuperarAcuseRequest", ReplyAction:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/RecuperarAcuseResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RecuperarAcuse(ByVal request As Certus.Timbrado.RecuperarAcuseRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Certus.Timbrado.RecuperarAcuseResponse
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/RecuperarAcuseCancelacion"& _ 
            "Request", ReplyAction:="http://cfdi.ws2.facturehoy.certus.com/WsEmisionTimbrado/RecuperarAcuseCancelacion"& _ 
            "Response"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RecuperarAcuseCancelacion(ByVal request As Certus.Timbrado.RecuperarAcuseCancelacionRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Certus.Timbrado.RecuperarAcuseCancelacionResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class wsResponseBO
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private arrayFoliosField() As wsItemCancelacionObj
        
        Private acuseField() As Byte
        
        Private arregloAcuseField()() As Byte
        
        Private cadenaOriginalField As String
        
        Private fechaHoraTimbradoField As Date
        
        Private fechaHoraTimbradoFieldSpecified As Boolean
        
        Private folioUDDIField As String
        
        Private isErrorField As Boolean
        
        Private isErrorFieldSpecified As Boolean
        
        Private messageField As String
        
        Private pDFField() As Byte
        
        Private rutaDescargaPDFField As String
        
        Private rutaDescargaXMLField As String
        
        Private selloDigitalEmisorField As String
        
        Private selloDigitalTimbreSATField As String
        
        Private xMLField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute("arreglo", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property arrayFolios() As wsItemCancelacionObj()
            Get
                Return Me.arrayFoliosField
            End Get
            Set
                Me.arrayFoliosField = value
                Me.RaisePropertyChanged("arrayFolios")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", Order:=1)>  _
        Public Property acuse() As Byte()
            Get
                Return Me.acuseField
            End Get
            Set
                Me.acuseField = value
                Me.RaisePropertyChanged("acuse")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("arregloAcuse", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true, Order:=2)>  _
        Public Property arregloAcuse() As Byte()()
            Get
                Return Me.arregloAcuseField
            End Get
            Set
                Me.arregloAcuseField = value
                Me.RaisePropertyChanged("arregloAcuse")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property cadenaOriginal() As String
            Get
                Return Me.cadenaOriginalField
            End Get
            Set
                Me.cadenaOriginalField = value
                Me.RaisePropertyChanged("cadenaOriginal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property fechaHoraTimbrado() As Date
            Get
                Return Me.fechaHoraTimbradoField
            End Get
            Set
                Me.fechaHoraTimbradoField = value
                Me.RaisePropertyChanged("fechaHoraTimbrado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property fechaHoraTimbradoSpecified() As Boolean
            Get
                Return Me.fechaHoraTimbradoFieldSpecified
            End Get
            Set
                Me.fechaHoraTimbradoFieldSpecified = value
                Me.RaisePropertyChanged("fechaHoraTimbradoSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property folioUDDI() As String
            Get
                Return Me.folioUDDIField
            End Get
            Set
                Me.folioUDDIField = value
                Me.RaisePropertyChanged("folioUDDI")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property isError() As Boolean
            Get
                Return Me.isErrorField
            End Get
            Set
                Me.isErrorField = value
                Me.RaisePropertyChanged("isError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property isErrorSpecified() As Boolean
            Get
                Return Me.isErrorFieldSpecified
            End Get
            Set
                Me.isErrorFieldSpecified = value
                Me.RaisePropertyChanged("isErrorSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", Order:=8)>  _
        Public Property PDF() As Byte()
            Get
                Return Me.pDFField
            End Get
            Set
                Me.pDFField = value
                Me.RaisePropertyChanged("PDF")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property rutaDescargaPDF() As String
            Get
                Return Me.rutaDescargaPDFField
            End Get
            Set
                Me.rutaDescargaPDFField = value
                Me.RaisePropertyChanged("rutaDescargaPDF")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property rutaDescargaXML() As String
            Get
                Return Me.rutaDescargaXMLField
            End Get
            Set
                Me.rutaDescargaXMLField = value
                Me.RaisePropertyChanged("rutaDescargaXML")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property selloDigitalEmisor() As String
            Get
                Return Me.selloDigitalEmisorField
            End Get
            Set
                Me.selloDigitalEmisorField = value
                Me.RaisePropertyChanged("selloDigitalEmisor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property selloDigitalTimbreSAT() As String
            Get
                Return Me.selloDigitalTimbreSATField
            End Get
            Set
                Me.selloDigitalTimbreSATField = value
                Me.RaisePropertyChanged("selloDigitalTimbreSAT")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", Order:=13)>  _
        Public Property XML() As Byte()
            Get
                Return Me.xMLField
            End Get
            Set
                Me.xMLField = value
                Me.RaisePropertyChanged("XML")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/")>  _
    Partial Public Class wsItemCancelacionObj
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private estatusField As Integer
        
        Private uUIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property estatus() As Integer
            Get
                Return Me.estatusField
            End Get
            Set
                Me.estatusField = value
                Me.RaisePropertyChanged("estatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
                Me.RaisePropertyChanged("UUID")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="EmitirTimbrar", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class EmitirTimbrarRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public contrasenia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public idServicio As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)>  _
        Public xml() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte)
            MyBase.New
            Me.usuario = usuario
            Me.contrasenia = contrasenia
            Me.idServicio = idServicio
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="EmitirTimbrarResponse", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class EmitirTimbrarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Certus.Timbrado.wsResponseBO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Certus.Timbrado.wsResponseBO)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="EmitirTimbrarTest", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class EmitirTimbrarTestRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public contrasenia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public idServicio As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary", IsNullable:=true)>  _
        Public xml() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte)
            MyBase.New
            Me.usuario = usuario
            Me.contrasenia = contrasenia
            Me.idServicio = idServicio
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="EmitirTimbrarTestResponse", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class EmitirTimbrarTestResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Certus.Timbrado.wsResponseBO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Certus.Timbrado.wsResponseBO)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Cancelar", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class CancelarRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public contrasenia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute("UUID", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public UUID() As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public keyEncode As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal contrasenia As String, ByVal UUID() As String, ByVal keyEncode As String)
            MyBase.New
            Me.usuario = usuario
            Me.contrasenia = contrasenia
            Me.UUID = UUID
            Me.keyEncode = keyEncode
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelarResponse", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class CancelarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Certus.Timbrado.wsResponseBO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Certus.Timbrado.wsResponseBO)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecuperarAcuse", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class RecuperarAcuseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public contrasenia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public UUID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal contrasenia As String, ByVal UUID As String)
            MyBase.New
            Me.usuario = usuario
            Me.contrasenia = contrasenia
            Me.UUID = UUID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecuperarAcuseResponse", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class RecuperarAcuseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Certus.Timbrado.wsResponseBO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Certus.Timbrado.wsResponseBO)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecuperarAcuseCancelacion", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class RecuperarAcuseCancelacionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public usuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public contrasenia As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public UUID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal contrasenia As String, ByVal UUID As String)
            MyBase.New
            Me.usuario = usuario
            Me.contrasenia = contrasenia
            Me.UUID = UUID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="RecuperarAcuseCancelacionResponse", WrapperNamespace:="http://cfdi.ws2.facturehoy.certus.com/", IsWrapped:=true)>  _
    Partial Public Class RecuperarAcuseCancelacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://cfdi.ws2.facturehoy.certus.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As Certus.Timbrado.wsResponseBO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As Certus.Timbrado.wsResponseBO)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WsEmisionTimbradoChannel
        Inherits Certus.Timbrado.WsEmisionTimbrado, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WsEmisionTimbradoClient
        Inherits System.ServiceModel.ClientBase(Of Certus.Timbrado.WsEmisionTimbrado)
        Implements Certus.Timbrado.WsEmisionTimbrado
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Certus_Timbrado_WsEmisionTimbrado_EmitirTimbrar(ByVal request As Certus.Timbrado.EmitirTimbrarRequest) As Certus.Timbrado.EmitirTimbrarResponse Implements Certus.Timbrado.WsEmisionTimbrado.EmitirTimbrar
            Return MyBase.Channel.EmitirTimbrar(request)
        End Function
        
        Public Function EmitirTimbrar(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte) As Certus.Timbrado.wsResponseBO
            Dim inValue As Certus.Timbrado.EmitirTimbrarRequest = New Certus.Timbrado.EmitirTimbrarRequest()
            inValue.usuario = usuario
            inValue.contrasenia = contrasenia
            inValue.idServicio = idServicio
            inValue.xml = xml
            Dim retVal As Certus.Timbrado.EmitirTimbrarResponse = CType(Me,Certus.Timbrado.WsEmisionTimbrado).EmitirTimbrar(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Certus_Timbrado_WsEmisionTimbrado_EmitirTimbrarTest(ByVal request As Certus.Timbrado.EmitirTimbrarTestRequest) As Certus.Timbrado.EmitirTimbrarTestResponse Implements Certus.Timbrado.WsEmisionTimbrado.EmitirTimbrarTest
            Return MyBase.Channel.EmitirTimbrarTest(request)
        End Function
        
        Public Function EmitirTimbrarTest(ByVal usuario As String, ByVal contrasenia As String, ByVal idServicio As Integer, ByVal xml() As Byte) As Certus.Timbrado.wsResponseBO
            Dim inValue As Certus.Timbrado.EmitirTimbrarTestRequest = New Certus.Timbrado.EmitirTimbrarTestRequest()
            inValue.usuario = usuario
            inValue.contrasenia = contrasenia
            inValue.idServicio = idServicio
            inValue.xml = xml
            Dim retVal As Certus.Timbrado.EmitirTimbrarTestResponse = CType(Me,Certus.Timbrado.WsEmisionTimbrado).EmitirTimbrarTest(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Certus_Timbrado_WsEmisionTimbrado_Cancelar(ByVal request As Certus.Timbrado.CancelarRequest) As Certus.Timbrado.CancelarResponse Implements Certus.Timbrado.WsEmisionTimbrado.Cancelar
            Return MyBase.Channel.Cancelar(request)
        End Function
        
        Public Function Cancelar(ByVal usuario As String, ByVal contrasenia As String, ByVal UUID() As String, ByVal keyEncode As String) As Certus.Timbrado.wsResponseBO
            Dim inValue As Certus.Timbrado.CancelarRequest = New Certus.Timbrado.CancelarRequest()
            inValue.usuario = usuario
            inValue.contrasenia = contrasenia
            inValue.UUID = UUID
            inValue.keyEncode = keyEncode
            Dim retVal As Certus.Timbrado.CancelarResponse = CType(Me,Certus.Timbrado.WsEmisionTimbrado).Cancelar(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Certus_Timbrado_WsEmisionTimbrado_RecuperarAcuse(ByVal request As Certus.Timbrado.RecuperarAcuseRequest) As Certus.Timbrado.RecuperarAcuseResponse Implements Certus.Timbrado.WsEmisionTimbrado.RecuperarAcuse
            Return MyBase.Channel.RecuperarAcuse(request)
        End Function
        
        Public Function RecuperarAcuse(ByVal usuario As String, ByVal contrasenia As String, ByVal UUID As String) As Certus.Timbrado.wsResponseBO
            Dim inValue As Certus.Timbrado.RecuperarAcuseRequest = New Certus.Timbrado.RecuperarAcuseRequest()
            inValue.usuario = usuario
            inValue.contrasenia = contrasenia
            inValue.UUID = UUID
            Dim retVal As Certus.Timbrado.RecuperarAcuseResponse = CType(Me,Certus.Timbrado.WsEmisionTimbrado).RecuperarAcuse(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Certus_Timbrado_WsEmisionTimbrado_RecuperarAcuseCancelacion(ByVal request As Certus.Timbrado.RecuperarAcuseCancelacionRequest) As Certus.Timbrado.RecuperarAcuseCancelacionResponse Implements Certus.Timbrado.WsEmisionTimbrado.RecuperarAcuseCancelacion
            Return MyBase.Channel.RecuperarAcuseCancelacion(request)
        End Function
        
        Public Function RecuperarAcuseCancelacion(ByVal usuario As String, ByVal contrasenia As String, ByVal UUID As String) As Certus.Timbrado.wsResponseBO
            Dim inValue As Certus.Timbrado.RecuperarAcuseCancelacionRequest = New Certus.Timbrado.RecuperarAcuseCancelacionRequest()
            inValue.usuario = usuario
            inValue.contrasenia = contrasenia
            inValue.UUID = UUID
            Dim retVal As Certus.Timbrado.RecuperarAcuseCancelacionResponse = CType(Me,Certus.Timbrado.WsEmisionTimbrado).RecuperarAcuseCancelacion(inValue)
            Return retVal.[return]
        End Function
    End Class
End Namespace
