'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.544
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DigitalFactura.Timbrar
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="../librerias/soap/", ConfigurationName:="DigitalFactura.Timbrar.FuncionesGeneralesFacPortType")>  _
    Public Interface FuncionesGeneralesFacPortType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://201.120.57.165/facturacion/wsdl/timbrev32.php/Generartimbre", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function Generartimbre(ByVal xml As String, ByVal id_sesion As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://201.120.57.165/facturacion/wsdl/timbrev32.php/fnIniciaSesion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function fnIniciaSesion(ByVal rfc As String, ByVal usuario As String, ByVal pass As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface FuncionesGeneralesFacPortTypeChannel
        Inherits DigitalFactura.Timbrar.FuncionesGeneralesFacPortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FuncionesGeneralesFacPortTypeClient
        Inherits System.ServiceModel.ClientBase(Of DigitalFactura.Timbrar.FuncionesGeneralesFacPortType)
        Implements DigitalFactura.Timbrar.FuncionesGeneralesFacPortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Generartimbre(ByVal xml As String, ByVal id_sesion As String) As String Implements DigitalFactura.Timbrar.FuncionesGeneralesFacPortType.Generartimbre
            Return MyBase.Channel.Generartimbre(xml, id_sesion)
        End Function
        
        Public Function fnIniciaSesion(ByVal rfc As String, ByVal usuario As String, ByVal pass As String) As String Implements DigitalFactura.Timbrar.FuncionesGeneralesFacPortType.fnIniciaSesion
            Return MyBase.Channel.fnIniciaSesion(rfc, usuario, pass)
        End Function
    End Class
End Namespace
